### ISSUE TITLE
Setanta + Regent doesn't fuse to Okuninushi (Closed)

### ISSUE THREAD

**Issue by daradux** [chinhodado/persona5_calculator#19]
edit [My mistake, a non-issue, "solved" (in quotes since it was a non-issue) and explained by @edmilsonrobson and @chinhodado below. I'm so embarrassed now, sorry again guys, and thank you for your time!]
old post below:
> Heyo,
> First of all, thanks for this amazing tool!
> I've been using it during 140+ hours of playing Persona 5. Today is the first time the tool was wrong.
> I tried fusing Setanta + Regent into Okuninushi according to [the calculator](https://chinhodado.github.io/persona5_calculator/index.html#/persona/Okuninushi)
> 
> This resulted in [Barong](https://chinhodado.github.io/persona5_calculator/index.html#/persona/Barong) instead. It wasn't a fusion "mishap". This is the first time the tool has ever differed from my game.
> 
> Thanks in advance and once again for making this amazing tool so simple to use - incredibly helpful mate!
> best regards,
> daradux
> 
> edit: I tried again and reproduced the problem. Setanta + Regent makes Barong. Thoth + Stone of Scone works (next on the list) and fuses into Okuninushi though.
> edit2: Provided image link for "proof": https://drive.google.com/open?id=0B8QTuSS6mwP6ME5xLVZKTW9HeTA

**Comment by edmilsonrobson** [comment]
According to the [Megaten Wikia](http://megamitensei.wikia.com/wiki/Treasure_Demon), these fusions with rare personas like Regent take the _current_ level of your ingredient persona (Setanta in this case) instead of their base level, so the resulting persona differs depending on Setanta's current level.

It probably creates an Okuninushi if Setanta's current level is closer to its base level (28), but as you level it up it will be creating more powerful personas in the Emperor arcana (such as Barong, which is the next "rank" after Okuninushi). 

I believe the calculator assumes that the ingredient persona's current level is its base level as well, but maybe @chinhodado could confirm here if I said something wrong. Just my 2 cents.

So... maybe try fusing a brand new Setanta at a lower level?

**Comment by edmilsonrobson** [comment]
By the way, maybe a visual disclaimer next to fusions with the special treasure personas would be handy for the users of the app. I could contribute to that if needed.

**Comment by daradux** [comment]
@ edmilsonrobson Thank you for your thorough explanation! 
That makes sense. My Setanta was way overleveled. The visual disclaimer you bring up sounds like a really good idea. I'm new to github and coding in general, but please let me know if there is any way I can contribute.

Thank you! 👍

**Comment by chinhodado** [comment]
The note for rare fusion is already there in the recipe section:

"Also, remember that rare persona fusion depends on your persona's current level."

**Comment by daradux** [comment]
@chinhodado Oh, I feel embarrassed now, I remember reading that when I started the game and also the app, but not getting exactly what it meant. Sorry guys!
