### ISSUE TITLE
DLC persona settings being ignored

### ISSUE THREAD

**Issue by notbutnot** [chinhodado/persona5_calculator#38]
DLC personas are being listed in lookups despite being disabled using the settings page

**Comment by chinhodado** [comment]
Can you give an example?

**Comment by notbutnot** [comment]
Turning off all dlc personas still brings up dlc and picaro dlc personas when doing searches.
![image](https://user-images.githubusercontent.com/43975269/61345420-17e95480-a823-11e9-91c4-8bf78ea15f50.png)
![image](https://user-images.githubusercontent.com/43975269/61345439-2c2d5180-a823-11e9-9357-63141c40ca44.png)

**Comment by chinhodado** [comment]
That's the main page which deliberately shows all persona, because by default all DLC persona are opt-in and I don't want to give the impression that something is missing from the outset. I do agree it can be confusing.

The setting should be respected when calculating persona fusion formula though.
