### ISSUE TITLE
Black Ooze

### ISSUE THREAD

**Issue by ashworthian** [chinhodado/persona5_calculator#44]
I noticed this being labelled at Level 18 and that at least FIVE of the different fusion recipes made Kaguya not Black Ooze.

**Comment by chinhodado** [comment]
Can you give some specific examples?

**Comment by ashworthian** [comment]
Archangel + Slime
Slime + High Pixie
Matador + Hua Po
Shiki-Ouji + Obaryion
Shiki-Ouji + Kodama

Those are the ones I remember.

**Comment by mrdanthedeadman** [comment]
That would be because while the calculator states the dlc persona cannot be fused to, they overwrite some of the fusion combinations when you have them and can be fused.  Can't remember the combination I used but there are a few that will create Orpheus.  Used the calculator for the vanilla version of the game, but it was also true in the vanilla if you had the dlc persona.

**Comment by ashworthian** [comment]
None of those Personas I attempted to fuse were DLC. They were fusing INTO a DLC Persona instead of Black Ooze. But thankfully on my restart I managed to capture Black Ooze in Kaneshiro’s Palace but that doesn’t help others.

**Comment by seriema** [comment]
> None of those Personas I attempted to fuse were DLC. They were fusing INTO a DLC Persona instead of Black Ooze.

That’s because you own the DLC. I made the same mistake. Go to settings in the calculator and check the DLC’s you have. Then the fusions will show the correct results.
