### ISSUE TITLE
Izanagi-no-Okami (Regular and Picaro) bugged

### ISSUE THREAD

**Issue by aofengen** [chinhodado/persona5_calculator#49]
[https://chinhodado.github.io/persona5_calculator/indexRoyal.html#/persona/Izanagi-no-Okami](url)
[https://chinhodado.github.io/persona5_calculator/indexRoyal.html#/persona/Izanagi-no-Okami%20Picaro](url) are both bugged - I get the following output when clicking on either:
![Izanagi-no-Okami](https://user-images.githubusercontent.com/30729364/81326131-5c223b80-9067-11ea-837d-b6e88b80b712.png)

Issue occurs on both Chrome and Edge (Chromium)

**Comment by mariomaster2004** [comment]
Bugged across all browsers for me too, tried a few and it was the same result

**Comment by aykrivwassup** [comment]
Same here. Happens every time. Not that it's _that_ major since they can a. only be fused by Advanced Fusion, b. can't fuse with any other normal Personas, and c. can only fuse with Treasure Demons and into each other, but it'd be nice to at least be able to see their movesets for personal reference.

**Comment by chinhodado** [comment]
Fixed
